---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./manifests/monitoring/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
  timeout: 5m0s
  wait: true
  patches:
    - patch: |-
        - op: replace
          path: /spec/values/alertmanager/enabled
          value: true
        - op: add
          path: /spec/valuesFrom
          value:
            - kind: Secret
              name: provider-url
              valuesKey: address
              targetPath: alertmanager.config.global.slack_api_url
      target:
        kind: HelmRelease
        name: kube-prometheus-stack

