apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  valuesFrom:
    - kind: Secret
      name: provider-url
      valuesKey: address
      targetPath: alertmanager.config.global.slack_api_url
  values:
    alertmanager:
      enabled: true
      global:
        resolve_timeout: 5m
      config:
        route:
          receiver: slack
          routes:
          - matchers:
            - severity="page"
            - alertname =~ "InfoInhibitor|Watchdog"
            receiver: slack
        receivers:
        - name: 'slack'
          slack_configs:
          - channel: "#random"
            send_reesolved: true
      alertmanagerSpec:
        alertmanagerConfigSelector:
          matchLabels:
            release: kube-prometheus-stack
        retention: 13h0
