---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  address: https://hooks.slack.com/services/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
  type: slack
